version: '3.8'
services:
  arovm:
    build: .
    container_name: arovm-web
    ports:
      - "80:8080"
    volumes:
      # Allows the container to manage the host's Docker engine
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://your-rds-endpoint:3306/arovm_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Vicky5349
    restart: on-failure
